//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClient.PersitanceService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PersitanceService.IPersitanceService")]
    public interface IPersitanceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersitanceService/PersistOrder", ReplyAction="http://tempuri.org/IPersitanceService/PersistOrderResponse")]
        string PersistOrder(string coffeOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersitanceService/PersistOrder", ReplyAction="http://tempuri.org/IPersitanceService/PersistOrderResponse")]
        System.Threading.Tasks.Task<string> PersistOrderAsync(string coffeOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersitanceService/getBadgeLastSelection", ReplyAction="http://tempuri.org/IPersitanceService/getBadgeLastSelectionResponse")]
        string getBadgeLastSelection(string badge);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersitanceService/getBadgeLastSelection", ReplyAction="http://tempuri.org/IPersitanceService/getBadgeLastSelectionResponse")]
        System.Threading.Tasks.Task<string> getBadgeLastSelectionAsync(string badge);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersitanceServiceChannel : WCFClient.PersitanceService.IPersitanceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersitanceServiceClient : System.ServiceModel.ClientBase<WCFClient.PersitanceService.IPersitanceService>, WCFClient.PersitanceService.IPersitanceService {
        
        public PersitanceServiceClient() {
        }
        
        public PersitanceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersitanceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersitanceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersitanceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string PersistOrder(string coffeOrder) {
            return base.Channel.PersistOrder(coffeOrder);
        }
        
        public System.Threading.Tasks.Task<string> PersistOrderAsync(string coffeOrder) {
            return base.Channel.PersistOrderAsync(coffeOrder);
        }
        
        public string getBadgeLastSelection(string badge) {
            return base.Channel.getBadgeLastSelection(badge);
        }
        
        public System.Threading.Tasks.Task<string> getBadgeLastSelectionAsync(string badge) {
            return base.Channel.getBadgeLastSelectionAsync(badge);
        }
    }
}
